### ISSUE TITLE
建议在Readme里，增加类似课程链接

### ISSUE THREAD

**Issue by zhuangbiaowei** [opensourceways/opensource101#7]
* 码云《开源指北》：  https://gitee.com/gitee-community/opensource-guide
* 庄表伟《借助开源项目，学习软件开发》：https://github.com/zhuangbiaowei/learn-with-open-source
* 开源社《针对大学生（国内）的开源教程》：https://github.com/kaiyuanshe/open_source_trainning_undergraduate
* 开源社《开源特训营》：https://github.com/kaiyuanshe/Open-source-training-camp

也许还有更多。

**Comment by liyongle** [comment]
在wiki有个[他山之石（可供参考的优秀课程）](https://github.com/opensourceways/opensource101/wiki/%E4%BB%96%E5%B1%B1%E4%B9%8B%E7%9F%B3%EF%BC%88%E5%8F%AF%E4%BE%9B%E5%8F%82%E8%80%83%E7%9A%84%E4%BC%98%E7%A7%80%E8%AF%BE%E7%A8%8B%EF%BC%89)，可以增加这些内容。

**Comment by zhuangbiaowei** [comment]
OK，我在那里加上

**Comment by liyongle** [comment]
> OK，我在那里加上

我刚刚加上了
